"""add_occurred_at_to_event_log

Revision ID: 791ff1d8fcdb
Revises: c39d2f7a11f1
Create Date: 2026-06-23 08:28:42.632154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791ff1d8fcdb'
down_revision: Union[str, Sequence[str], None] = 'c39d2f7a11f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_log', sa.Column('occurred_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_event_log_occurred_at'), 'event_log', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_log_occurred_at'), table_name='event_log')
    op.drop_column('event_log', 'occurred_at')
    # ### end Alembic commands ###
