"""add_user_stories_table

Revision ID: ab95e433868c
Revises: 791ff1d8fcdb
Create Date: 2026-06-23 08:37:29.947175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab95e433868c'
down_revision: Union[str, Sequence[str], None] = '791ff1d8fcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sprint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acceptance_criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_is_deleted'), 'user_stories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_stories_project_id'), 'user_stories', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_stories_sprint_id'), 'user_stories', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_user_stories_status'), 'user_stories', ['status'], unique=False)
    op.create_index(op.f('ix_user_stories_title'), 'user_stories', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stories_title'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_status'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_sprint_id'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_project_id'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_is_deleted'), table_name='user_stories')
    op.drop_table('user_stories')
    # ### end Alembic commands ###
